---
title: "R News"
author: "Michael Kahle"
date: "24 11 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R News

# https://cran.r-project.org/web/packages/newsanchor/vignettes/usage-newsanchor.html
# https://cran.r-project.org/web/packages/newsanchor/newsanchor.pdf
# https://newsapi.org

# tidytext
# https://cran.r-project.org/web/packages/tidytext/vignettes/tidytext.html


```{r init}
library(dplyr)
library(newsanchor)
library(tidytext)
library(stopwords)
library(wordcloud)

#set_api_key(api_key = "12345", path = "~/.Renviron")
Sys.setenv("NEWS_API_KEY" = "12345")
#Sys.getenv("NEWS_API_KEY")


```

```{r query}

results0 <- get_headlines(query = "drought", country="de" )
results1 <- get_everything_all(query = "drought", language = "en" )
results2 <- get_everything(query = "Dürre", language = "de")

results3 <- get_headlines_all(query = "Dürre", country="de")
results4 <- get_everything_all(query = "Dürre", language = "de")
results5 <- get_everything_all(query = "Schnee", language = "de")
results6 <- get_everything_all(query = "snow", language = "en")
results7 <- get_everything_all(query = "wildfire", language = "en")
results8 <- get_everything_all(query = "Waldbrand", language = "de")

results <- get_everything(query = "Trump")


results$metadata
res1 = results1$results_df
res2 = results2$results_df
res4 = results4$results_df
res5 = results5$results_df
res6 = results6$results_df
res7 = results7$results_df
res8 = results8$results_df


```


## Analyse
```{r analyse}



res2$all = paste(res2$title, res2$description, res2$content)

words2 <- res2 %>%
  unnest_tokens(word, all)

clean2 <- words2 %>%
  anti_join(get_stopwords("de"))

most2 <- clean2 %>%
  count(word, sort = TRUE) 



clean2 %>%
  count(word) %>%
  with(wordcloud(word, n, max.words = 100))



bing <- get_sentiments("bing")

library(stringr)
library(tidyr)
library(ggplot2)

res7$all = paste(res7$title, res7$description, res7$content)

words7 <- res7 %>%
  unnest_tokens(word, all)

sentiment7 <- words7 %>%
  inner_join(bing) %>%
  count(published_at, sentiment) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative)


ggplot(sentiment7, aes(published_at, sentiment)) +
  geom_bar(stat = "identity", show.legend = FALSE) 


library(reshape2)


res6$all = paste(res6$title, res6$description, res6$content)

words6 <- res6 %>%
  unnest_tokens(word, all)

words6 %>%
  inner_join(bing) %>%
  count(word, sentiment, sort = TRUE) %>%
  acast(word ~ sentiment, value.var = "n", fill = 0) %>%
  comparison.cloud(colors = c("#F8766D", "#00BFC4"),
                   max.words = 100)

```

## Visualize
```{r map, fig.width=50, fig.height=50}

```
